contracts: prevent hoisting of typechain modules
If some of the typechain modules get hoisted, it can result in hardhat
typechain failing with:

    Error: Couldn't find ethers-v5. Tried loading: @typechain/ethers-v5, typechain-target-ethers-v5, /home/adam/blockchain/Panther/git/zkp-staking/contracts/ethers-v5.
    Perhaps you forgot to install @typechain/ethers-v5?

This appears to be a known issue:

- https://github.com/dethcrypto/TypeChain/issues/620

so work around it by preventing hoisting of typechain stuff.